/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagym;

/**
 *
 * @author chemi
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import sistemagym.conexionBD;

public class empleados extends javax.swing.JFrame {

    /**
     * Creates new form empleados
     */
    public empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Empleados");
        setResizable(false);
        setSize(600, 500);
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);

        // Etiquetas y campos
        javax.swing.JLabel lblId = new javax.swing.JLabel("ID:");
        javax.swing.JLabel lblNombre = new javax.swing.JLabel("Nombre:");
        javax.swing.JLabel lblApellido = new javax.swing.JLabel("Apellido:");
        javax.swing.JLabel lblFechaNac = new javax.swing.JLabel("Fecha Nacimiento (YYYY-MM-DD):");
        javax.swing.JLabel lblTelefono = new javax.swing.JLabel("Teléfono:");
        javax.swing.JLabel lblEmail = new javax.swing.JLabel("Email:");
        javax.swing.JLabel lblFechaCont = new javax.swing.JLabel("Fecha Contratación (YYYY-MM-DD):");
        javax.swing.JLabel lblSalario = new javax.swing.JLabel("Salario:");
        javax.swing.JLabel lblCargo = new javax.swing.JLabel("Cargo:");
        javax.swing.JLabel lblEstado = new javax.swing.JLabel("Estado:");

        javax.swing.JTextField txtId = new javax.swing.JTextField();
        javax.swing.JTextField txtNombre = new javax.swing.JTextField();
        javax.swing.JTextField txtApellido = new javax.swing.JTextField();
        javax.swing.JTextField txtFechaNac = new javax.swing.JTextField();
        javax.swing.JTextField txtTelefono = new javax.swing.JTextField();
        javax.swing.JTextField txtEmail = new javax.swing.JTextField();
        javax.swing.JTextField txtFechaCont = new javax.swing.JTextField();
        javax.swing.JTextField txtSalario = new javax.swing.JTextField();
        javax.swing.JTextField txtCargo = new javax.swing.JTextField();
        javax.swing.JComboBox<String> cmbEstado = new javax.swing.JComboBox<>(new String[]{"activo", "inactivo"});

        // Botones
        javax.swing.JButton btnGuardar = new javax.swing.JButton("Guardar");
        javax.swing.JButton btnBuscar = new javax.swing.JButton("Buscar");
        javax.swing.JButton btnEliminar = new javax.swing.JButton("Eliminar");
        javax.swing.JButton btnLimpiar = new javax.swing.JButton("Limpiar");

        // Posicionamiento manual (null layout)
        int xLbl = 30, xTxt = 220, y = 30, sep = 35, wLbl = 180, wTxt = 300, h = 25;
        lblId.setBounds(xLbl, y, wLbl, h); txtId.setBounds(xTxt, y, wTxt, h); y += sep;
        lblNombre.setBounds(xLbl, y, wLbl, h); txtNombre.setBounds(xTxt, y, wTxt, h); y += sep;
        lblApellido.setBounds(xLbl, y, wLbl, h); txtApellido.setBounds(xTxt, y, wTxt, h); y += sep;
        lblFechaNac.setBounds(xLbl, y, wLbl, h); txtFechaNac.setBounds(xTxt, y, wTxt, h); y += sep;
        lblTelefono.setBounds(xLbl, y, wLbl, h); txtTelefono.setBounds(xTxt, y, wTxt, h); y += sep;
        lblEmail.setBounds(xLbl, y, wLbl, h); txtEmail.setBounds(xTxt, y, wTxt, h); y += sep;
        lblFechaCont.setBounds(xLbl, y, wLbl, h); txtFechaCont.setBounds(xTxt, y, wTxt, h); y += sep;
        lblSalario.setBounds(xLbl, y, wLbl, h); txtSalario.setBounds(xTxt, y, wTxt, h); y += sep;
        lblCargo.setBounds(xLbl, y, wLbl, h); txtCargo.setBounds(xTxt, y, wTxt, h); y += sep;
        lblEstado.setBounds(xLbl, y, wLbl, h); cmbEstado.setBounds(xTxt, y, wTxt, h); y += sep;

        btnGuardar.setBounds(60, y, 100, h);
        btnBuscar.setBounds(180, y, 100, h);
        btnEliminar.setBounds(300, y, 100, h);
        btnLimpiar.setBounds(420, y, 100, h);

        add(lblId); add(txtId);
        add(lblNombre); add(txtNombre);
        add(lblApellido); add(txtApellido);
        add(lblFechaNac); add(txtFechaNac);
        add(lblTelefono); add(txtTelefono);
        add(lblEmail); add(txtEmail);
        add(lblFechaCont); add(txtFechaCont);
        add(lblSalario); add(txtSalario);
        add(lblCargo); add(txtCargo);
        add(lblEstado); add(cmbEstado);
        add(btnGuardar); add(btnBuscar); add(btnEliminar); add(btnLimpiar);

        // Acción Botón Guardar
        btnGuardar.addActionListener(e -> {
            if (txtNombre.getText().trim().isEmpty() || txtApellido.getText().trim().isEmpty() ||
                txtFechaNac.getText().trim().isEmpty() || txtTelefono.getText().trim().isEmpty() ||
                txtEmail.getText().trim().isEmpty() || txtFechaCont.getText().trim().isEmpty() ||
                txtSalario.getText().trim().isEmpty() || txtCargo.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios (excepto ID, que es autogenerado)");
                return;
            }
            try (Connection conn = conexionBD.getConnection()) {
                String sql = "INSERT INTO empleados (nombre, apellido, fecha_nacimiento, telefono, email, fecha_contratacion, salario, cargo, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtNombre.getText().trim());
                pst.setString(2, txtApellido.getText().trim());
                pst.setDate(3, java.sql.Date.valueOf(txtFechaNac.getText().trim()));
                pst.setString(4, txtTelefono.getText().trim());
                pst.setString(5, txtEmail.getText().trim());
                pst.setDate(6, java.sql.Date.valueOf(txtFechaCont.getText().trim()));
                pst.setBigDecimal(7, new java.math.BigDecimal(txtSalario.getText().trim()));
                pst.setString(8, txtCargo.getText().trim());
                pst.setString(9, cmbEstado.getSelectedItem().toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Empleado guardado correctamente.");
                limpiarCampos();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Verifica los formatos de fecha (YYYY-MM-DD) y salario.");
            }
        });

        // Acción Botón Buscar
        btnBuscar.addActionListener(e -> {
            if (txtId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingresa el ID a buscar.");
                return;
            }
            try (Connection conn = conexionBD.getConnection()) {
                String sql = "SELECT * FROM empleados WHERE id = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(txtId.getText().trim()));
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    txtNombre.setText(rs.getString("nombre"));
                    txtApellido.setText(rs.getString("apellido"));
                    txtFechaNac.setText(rs.getString("fecha_nacimiento"));
                    txtTelefono.setText(rs.getString("telefono"));
                    txtEmail.setText(rs.getString("email"));
                    txtFechaCont.setText(rs.getString("fecha_contratacion"));
                    txtSalario.setText(rs.getString("salario"));
                    txtCargo.setText(rs.getString("cargo"));
                    cmbEstado.setSelectedItem(rs.getString("estado"));
                    JOptionPane.showMessageDialog(this, "Empleado encontrado.");
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el empleado.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al buscar: " + ex.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ID inválido.");
            }
        });

        // Acción Botón Eliminar
        btnEliminar.addActionListener(e -> {
            if (txtId.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingresa el ID a eliminar.");
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try (Connection conn = conexionBD.getConnection()) {
                    String sql = "DELETE FROM empleados WHERE id = ?";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setInt(1, Integer.parseInt(txtId.getText().trim()));
                    int rows = pst.executeUpdate();
                    if (rows > 0) {
                        JOptionPane.showMessageDialog(this, "Empleado eliminado.");
                        limpiarCampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se encontró el empleado.");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "ID inválido.");
                }
            }
        });

        // Acción Botón Limpiar
        btnLimpiar.addActionListener(e -> limpiarCampos());

        // Método para limpiar campos
        limpiarCampos();
    }

    private void limpiarCampos() {
        for (java.awt.Component c : getContentPane().getComponents()) {
            if (c instanceof javax.swing.JTextField) {
                ((javax.swing.JTextField)c).setText("");
            }
            if (c instanceof javax.swing.JComboBox) {
                ((javax.swing.JComboBox<?>)c).setSelectedIndex(0);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
